language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build app
  - docker-compose build ci-tests

script:
  - docker-compose run --rm ci-tests

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
