version: "2"

services:

  app:
    build: .
    image: keboola/gooddata-writer
    tty: true
    command: bash
    volumes:
      - ./:/code

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: composer build
    volumes:
      - ./:/code
    environment:
      - GD_PID
      - GD_PID_2
      - GD_USERNAME
      - GD_PASSWORD
      - KBC_TOKEN
      - PROVISIONING_URL

  ci-tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: composer build
    environment:
      - GD_PID
      - GD_PID_2
      - GD_USERNAME
      - GD_PASSWORD
      - KBC_TOKEN
      - PROVISIONING_URL
